### ISSUE TITLE
Dockerfile issue: generate healthcheck:install requires DB connection

### ISSUE THREAD

**Issue by universam1** [linqueta/rails-healthcheck#34]
Having an issue to include this gem into a docker container, where we bundle during build time.

Apparently running
```Dockerfile
RUN bundle exec rails generate healthcheck:install
```

results in call to DB which is of course not given during this build phase.
```
+ bundle exec rails generate healthcheck:install
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `initialize': could not translate host name "db" to address: Try again (PG::ConnectionBad)
	from /usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `new'
	from /usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
...
```

Is it possible to skip the install method in a different way?

**Comment by linqueta** [comment]
Hey man, 

As I can see, this problem is because when you type `rails generate <generator>`, Rails will up the app, so, it'll require its Postres connection. 

But, as at this time you are building the app yet, you probably  don't have the postgres connection. 

So, my suggestions are two: 
1. Run this command out of your Dockerfile, so locally. After that run to build your image and I think that all will be ok.
2. If you really need this setup during the build, run it after have a db connection, you can set a command in your Docker Compose's server service to run this generator. Don't forget the db dependency.

**Comment by universam1** [comment]
Thank you for the response!

None of these options are applicable for us, since we are building the immutable image in a pipeline where no DB is available.

I went now the hacky way and copy the configuration file and the `sed` the route manually, that works as of now.

**Comment by linqueta** [comment]
If it works for you, at this [commit](https://github.com/linqueta/rails-healthcheck/commit/3cc1ce89813b5c8a3b9d3b40397cb51fa6dc90eb#diff-562b1aa2dfe80e7594293fdf51290097) the gem have used a simple rake task, where it doesn't require the db connection.

You can fork and bring again this rake task, or, implement it in your app and run during your build.
